import express from 'express';

const router = express.Router();

let pool;

router.setPool = (p) => {
  pool = p;
};

const initSectionsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS sustainability_sections (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      badge VARCHAR(50) DEFAULT '',
      text TEXT,
      sort_order INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
  `);
};

const DEFAULT_SECTIONS = [
  { title: '0. ESG Strategy: Driving Digital Sustainability', badge: null, text: "Satesoft's ESG strategy integrates environmental stewardship, social responsibility, and governance into our core business model. We recognize that technology companies have a unique opportunity—and responsibility—to drive sustainable digital transformation across Africa and beyond. Our strategy is built on science-based targets, stakeholder engagement, and transparent disclosure. We align with the UN Sustainable Development Goals (SDGs), focusing on affordable clean energy (SDG 7), decent work and economic growth (SDG 8), industry innovation (SDG 9), and climate action (SDG 13). By embedding sustainability into product design, operations, and partnerships, we aim to create long-term value for our clients, employees, and the communities we serve.", sort_order: 0 },
  { title: '1. Circular Economy & E-Waste Stewardship', badge: 'COLLAPSIBLE', text: 'We are committed to minimizing electronic waste through responsible device lifecycle management. Our initiatives include partnerships with certified e-waste recyclers, refurbishment programs for retired hardware, and supplier requirements for take-back schemes. By 2027, we aim to divert 100% of our e-waste from landfills and extend the useful life of devices through repair, reuse, and responsible material recovery. We also work with clients to establish circular IT procurement policies that prioritize durability, repairability, and end-of-life recycling.', sort_order: 1 },
  { title: '2. Decarbonizing Digital Infrastructure', badge: 'COLLAPSIBLE', text: 'Our digital infrastructure is being decarbonized through renewable energy procurement, energy-efficient data center design, and carbon-aware cloud architectures. We track Scope 1, 2, and 3 emissions and publish annual carbon footprint reports. Our target is a 50% reduction in absolute emissions by 2028. We optimize compute workloads to run during periods of low grid carbon intensity, consolidate underutilized servers, and invest in next-generation cooling technologies. Our cloud partners are selected partly based on their renewable energy commitments and carbon transparency.', sort_order: 2 },
  { title: '3. Low-Carbon Service Delivery', badge: 'COLLAPSIBLE', text: 'We optimize our software and services for energy efficiency. From lightweight code deployments to edge computing strategies that reduce data transmission distances, every layer of our service delivery model is evaluated for carbon impact. We help clients measure and reduce the carbon footprint of their digital operations through sustainability dashboards, green software audits, and carbon-aware architecture guidance. Our engineering teams follow green coding practices that minimize CPU cycles, memory usage, and network transfers—reducing both cost and environmental impact.', sort_order: 3 },
  { title: '4. Ecosystem Protection & Climate Resilience', badge: 'COLLAPSIBLE', text: 'Beyond our operational footprint, we invest in ecosystem restoration and climate resilience projects. This includes reforestation partnerships, water conservation programs in our offices, and climate-risk assessments for our supply chain. We align with the Task Force on Climate-related Financial Disclosures (TCFD) framework and integrate climate risk into our enterprise risk management process. Our community programs support climate-smart agriculture, wetland restoration, and biodiversity monitoring using our own technology platforms.', sort_order: 4 },
  { title: '5. Social Impact: Enabling Client Sustainability', badge: 'COLLAPSIBLE', text: 'Our greatest impact comes from empowering clients to achieve their sustainability goals. Through Duqact, we provide supply chain transparency tools that reduce food waste and logistics emissions. Through FoundDocument, we enable paperless operations that save millions of pages annually. We measure the avoided emissions generated by client use of our platforms and publish these impact metrics in our annual ESG report. Our digital literacy programs also ensure that sustainability benefits are accessible to small businesses and informal sector operators across Africa.', sort_order: 5 },
  { title: '6. Governance & Accountability', badge: 'COLLAPSIBLE', text: 'Sustainability governance is embedded in our board structure and executive compensation. Our ESG Committee meets quarterly to review targets, risks, and disclosures. We undergo third-party audits of our environmental data and maintain transparent reporting aligned with GRI and SASB standards. Our code of conduct applies to all employees, suppliers, and partners, with zero tolerance for greenwashing or misleading environmental claims. We maintain a whistleblower policy and independent oversight for all ESG-related disclosures.', sort_order: 6 }
];

router.get('/sections', async (req, res) => {
  try {
    await initSectionsTable();
    const [rows] = await pool.query('SELECT * FROM sustainability_sections ORDER BY sort_order ASC, id ASC');
    if (rows.length === 0) {
      for (const section of DEFAULT_SECTIONS) {
        await pool.query('INSERT INTO sustainability_sections (title, badge, text, sort_order) VALUES (?, ?, ?, ?)', [section.title, section.badge, section.text, section.sort_order]);
      }
      const [newRows] = await pool.query('SELECT * FROM sustainability_sections ORDER BY sort_order ASC, id ASC');
      return res.json(newRows);
    }
    res.json(rows);
  } catch (error) {
    console.error('Fetch Sections Error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/section', async (req, res) => {
  try {
    await initSectionsTable();
    let { title, badge, text } = req.body;
    const cleanTitle = (title || '').replace(/^(\d+\.|\s)+/g, '').trim();
    const [maxRows] = await pool.query('SELECT MAX(sort_order) AS max_sort FROM sustainability_sections');
    const nextSort = (maxRows[0]?.max_sort ?? -1) + 1;
    const [result] = await pool.query(
      'INSERT INTO sustainability_sections (title, badge, text, sort_order) VALUES (?, ?, ?, ?)',
      [cleanTitle, badge || '', text || '', nextSort]
    );
    const [rows] = await pool.query('SELECT * FROM sustainability_sections WHERE id = ?', [result.insertId]);
    res.status(201).json(rows[0]);
  } catch (error) {
    console.error('Add Section Error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

router.put('/section/:id', async (req, res) => {
  try {
    await initSectionsTable();
    const { id } = req.params;
    let { title, badge, text, sort_order } = req.body;
    const cleanTitle = (title || '').replace(/^(\d+\.|\s)+/g, '').trim();
    await pool.query(
      'UPDATE sustainability_sections SET title = ?, badge = ?, text = ?, sort_order = ? WHERE id = ?',
      [cleanTitle, badge || '', text || '', sort_order ?? 0, id]
    );
    const [updated] = await pool.query('SELECT * FROM sustainability_sections WHERE id = ?', [id]);
    res.json(updated[0]);
  } catch (error) {
    console.error('Update Section Error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

router.delete('/section/:id', async (req, res) => {
  try {
    await initSectionsTable();
    const { id } = req.params;
    await pool.query('DELETE FROM sustainability_sections WHERE id = ?', [id]);
    res.json({ success: true });
  } catch (error) {
    console.error('Delete Section Error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/reset-seed', async (req, res) => {
  try {
    await pool.query(`DROP TABLE IF EXISTS sustainability_sections`);
    await initSectionsTable();
    for (const section of DEFAULT_SECTIONS) {
      await pool.query('INSERT INTO sustainability_sections (title, badge, text, sort_order) VALUES (?, ?, ?, ?)', [section.title, section.badge, section.text, section.sort_order]);
    }
    const [rows] = await pool.query('SELECT * FROM sustainability_sections ORDER BY sort_order ASC, id ASC');
    return res.json({ message: 'Database successfully reset and seeded', data: rows });
  } catch (err) {
    console.error('Reset Seed Failed:', err);
    return res.status(500).json({ error: 'Failed to reset database' });
  }
});

export default router;
