import React, { useState, useEffect } from 'react';
import api from '../api/axios';

const DEFAULT_SUSTAINABILITY_SECTIONS = [
  {
    id: 'sec-0',
    number: '0.',
    title: 'ESG Strategy: Driving Digital Sustainability',
    content: `Satesoft's ESG strategy integrates environmental stewardship, social responsibility, and governance into our core business model. We recognize that technology companies have a unique opportunity—and responsibility—to drive sustainable digital transformation across Africa and beyond. Our strategy is built on science-based targets, stakeholder engagement, and transparent disclosure. We align with the UN Sustainable Development Goals (SDGs), focusing on affordable clean energy (SDG 7), decent work and economic growth (SDG 8), industry innovation (SDG 9), and climate action (SDG 13). By embedding sustainability into product design, operations, and partnerships, we aim to create long-term value for our clients, employees, and the communities we serve.`
  },
  {
    id: 'sec-1',
    number: '1.',
    title: 'Pillar 1: Circular Economy & E-Waste Stewardship',
    content: `We are committed to minimizing electronic waste through responsible device lifecycle management. Our initiatives include partnerships with certified e-waste recyclers, refurbishment programs for retired hardware, and supplier requirements for take-back schemes. By 2027, we aim to divert 100% of our e-waste from landfills and extend the useful life of devices through repair, reuse, and responsible material recovery. We also work with clients to establish circular IT procurement policies that prioritize durability, repairability, and end-of-life recycling.`
  },
  {
    id: 'sec-2',
    number: '2.',
    title: 'Pillar 2: Decarbonizing Digital Infrastructure',
    content: `Our digital infrastructure is being decarbonized through renewable energy procurement, energy-efficient data center design, and carbon-aware cloud architectures. We track Scope 1, 2, and 3 emissions and publish annual carbon footprint reports. Our target is a 50% reduction in absolute emissions by 2028. We optimize compute workloads to run during periods of low grid carbon intensity, consolidate underutilized servers, and invest in next-generation cooling technologies. Our cloud partners are selected partly based on their renewable energy commitments and carbon transparency.`
  },
  {
    id: 'sec-3',
    number: '3.',
    title: 'Pillar 3: Low-Carbon Service Delivery',
    content: `We optimize our software and services for energy efficiency. From lightweight code deployments to edge computing strategies that reduce data transmission distances, every layer of our service delivery model is evaluated for carbon impact. We help clients measure and reduce the carbon footprint of their digital operations through sustainability dashboards, green software audits, and carbon-aware architecture guidance. Our engineering teams follow green coding practices that minimize CPU cycles, memory usage, and network transfers—reducing both cost and environmental impact.`
  },
  {
    id: 'sec-4',
    number: '4.',
    title: 'Pillar 4: Ecosystem Protection & Climate Resilience',
    content: `Beyond our operational footprint, we invest in ecosystem restoration and climate resilience projects. This includes reforestation partnerships, water conservation programs in our offices, and climate-risk assessments for our supply chain. We align with the Task Force on Climate-related Financial Disclosures (TCFD) framework and integrate climate risk into our enterprise risk management process. Our community programs support climate-smart agriculture, wetland restoration, and biodiversity monitoring using our own technology platforms.`
  },
  {
    id: 'sec-5',
    number: '5.',
    title: 'Social Impact: Enabling Client Sustainability',
    content: `Our greatest impact comes from empowering clients to achieve their sustainability goals. Through Duqact, we provide supply chain transparency tools that reduce food waste and logistics emissions. Through FoundDocument, we enable paperless operations that save millions of pages annually. We measure the avoided emissions generated by client use of our platforms and publish these impact metrics in our annual ESG report. Our digital literacy programs also ensure that sustainability benefits are accessible to small businesses and informal sector operators across Africa.`
  },
  {
    id: 'sec-6',
    number: '6.',
    title: 'Governance & Accountability',
    content: `Sustainability governance is embedded in our board structure and executive compensation. Our ESG Committee meets quarterly to review targets, risks, and disclosures. We undergo third-party audits of our environmental data and maintain transparent reporting aligned with GRI and SASB standards. Our code of conduct applies to all employees, suppliers, and partners, with zero tolerance for greenwashing or misleading environmental claims. We maintain a whistleblower policy and independent oversight for all ESG-related disclosures.`
  }
];

const normalizeSection = (sec, idx) => {
  const rawTitle = String(sec.title || sec.text || '').replace(/^(\d+[\.\s\-\)]*)+/g, '').trim();
  const rawContent = sec.text || sec.content || '';
  return {
    id: sec.id || `sec-${idx}`,
    number: rawTitle.toLowerCase().includes('introduction') ? '' : `${idx}.`,
    title: rawTitle || `Section ${idx + 1}`,
    content: rawContent,
    badge: sec.badge || null
  };
};

const Sustainability = () => {
  const [sections, setSections] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [activeSection, setActiveSection] = useState('');

  useEffect(() => {
    const fetchPublicSections = async () => {
      try {
        const response = await api.get('/legal/sustainability/sections');
        const data = Array.isArray(response.data) ? response.data : (response.data.sections || []);
        if (data.length > 0) {
          setSections(data.map(normalizeSection));
        } else {
          setSections(DEFAULT_SUSTAINABILITY_SECTIONS.map(normalizeSection));
        }
      } catch (err) {
        console.error('Error loading public sustainability content:', err);
        setSections(DEFAULT_SUSTAINABILITY_SECTIONS.map(normalizeSection));
      } finally {
        setLoading(false);
      }
    };

    fetchPublicSections();
  }, []);

  useEffect(() => {
    if (sections.length > 0 && !activeSection) {
      setActiveSection(sections[0].id);
    }
  }, [sections, activeSection]);

  const displaySections = sections.map((sec, idx) => ({
    ...sec,
    number: sec.title.toLowerCase().includes('introduction') ? '' : `${idx}.`,
    title: String(sec.title || '').replace(/^(\d+[\.\s\-\)]*)+/g, '').trim()
  }));

  const filteredSections = displaySections.filter(sec =>
    sec.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    sec.content.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handlePrint = () => {
    window.print();
  };

  const scrollToSection = (e, id) => {
    e.preventDefault();
    setActiveSection(id);
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  useEffect(() => {
    const container = document.getElementById('doc-scroll-container');
    if (!container) return;

    const handleScroll = () => {
      const sectionElements = filteredSections.map(sec => ({
        id: sec.id,
        element: document.getElementById(sec.id)
      }));

      const current = sectionElements.find(section => {
        if (!section.element) return false;
        const rect = section.element.getBoundingClientRect();
        return rect.top <= 120 && rect.bottom >= 120;
      });

      if (current) {
        setActiveSection(current.id);
      }
    };

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, [filteredSections]);

  if (loading) {
    return (
      <div className="h-screen bg-slate-50 p-4 sm:p-6 lg:p-8 font-sans overflow-hidden flex items-center justify-center">
        <div className="text-sm text-slate-500">Loading sustainability content...</div>
      </div>
    );
  }

  return (
    <div className="h-screen bg-slate-50 p-4 sm:p-6 lg:p-8 font-sans overflow-hidden flex flex-col">
      <div className="max-w-7xl w-full mx-auto bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-full">

        {/* Header */}
        <div className="py-6 px-6 border-b border-slate-100 bg-white shrink-0">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">

            <div>
              <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-[#6bb200]">
                Sustainability & ESG Report
              </h1>
              <p className="text-sm font-bold text-[#6bb200] mt-0.5 italic">
                Environmental, Social, and Governance Framework
              </p>
            </div>

            <div className="flex items-center gap-3 no-print">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Search sections..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-48 sm:w-64 text-xs bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 pl-8 focus:outline-none focus:border-[#6bb200] transition-all"
                />
                <svg
                  className="w-4 h-4 text-slate-400 absolute left-2.5 top-2.5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </div>

              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 text-xs font-semibold text-white bg-[#6bb200] hover:bg-[#5a9e00] px-3.5 py-2 rounded-lg transition-colors shadow-sm shrink-0"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                <span>Print Report</span>
              </button>
            </div>

          </div>

          <div className="flex items-center gap-4 text-xs font-semibold text-slate-400 mt-3 pt-3 border-t border-slate-50">
            <span>EFFECTIVE: 01.04.2025</span>
            <span>•</span>
            <span>VERSION 1.0.0</span>
          </div>
        </div>

        {/* Content Body */}
        <div className="flex flex-1 overflow-hidden p-6 lg:p-8 relative">

          {/* Sidebar */}
          <div className="w-full lg:w-1/4 border-r border-slate-100 pr-4 hidden lg:block h-full overflow-y-auto shrink-0 no-print">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 sticky top-0 bg-white py-1 z-10">
              Table of Contents
            </h3>

            {filteredSections.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No sections found.</p>
            ) : (
              <nav className="space-y-1 text-xs">
                {filteredSections.map((sec) => (
                  <a
                    key={sec.id}
                    href={`#${sec.id}`}
                    onClick={(e) => scrollToSection(e, sec.id)}
                    className={`block py-1.5 px-2 rounded-md transition-all font-medium ${
                      activeSection === sec.id
                        ? 'bg-[#e8f5e9] text-[#6bb200] font-bold border-l-2 border-[#6bb200]'
                        : 'text-slate-600 hover:text-[#6bb200] hover:bg-slate-50'
                    }`}
                  >
                    {sec.number} {sec.title}
                  </a>
                ))}
              </nav>
            )}
          </div>

          {/* Document Section Text */}
          <div id="doc-scroll-container" className="w-full lg:w-3/4 h-full overflow-y-auto pl-0 lg:pl-8 space-y-10 text-sm text-slate-700 leading-relaxed pr-2">
            {filteredSections.map((sec, idx) => (
              <section key={sec.id} id={sec.id} className={idx > 0 ? 'scroll-mt-6 pt-6 border-t border-slate-100' : 'scroll-mt-6'}>
                <h2 className="text-lg font-bold text-[#70B312] mb-3">
                  {sec.number} {sec.title}
                </h2>
                {sec.badge && (
                  <span className="inline-block text-[10px] font-bold tracking-wider uppercase bg-slate-100 text-slate-500 px-2 py-0.5 rounded mb-2">
                    {sec.badge}
                  </span>
                )}
                <p className="whitespace-pre-wrap break-words">{sec.content}</p>
              </section>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-slate-100 py-6 text-center text-xs text-slate-400 bg-slate-50/50">
          <p className="font-semibold text-slate-600">Confidential — Satesoft Corporation Limited</p>
          <p className="font-bold text-[#6bb200] mt-0.5">Satesoft Corporation Limited — Your Innovation Partner</p>
        </div>

      </div>
    </div>
  );
};

export default Sustainability;
