import React, { useState, useEffect } from 'react';
import api from '../../api/axios';

const DEFAULT_SUSTAINABILITY_SECTIONS = [
  { id: 'sec-1', sort_order: 0, title: '0. ESG Strategy: Driving Digital Sustainability', text: "Satesoft's ESG strategy integrates environmental stewardship, social responsibility, and governance into our core business model. We recognize that technology companies have a unique opportunity—and responsibility—to drive sustainable digital transformation across Africa and beyond. Our strategy is built on science-based targets, stakeholder engagement, and transparent disclosure. We align with the UN Sustainable Development Goals (SDGs), focusing on affordable clean energy (SDG 7), decent work and economic growth (SDG 8), industry innovation (SDG 9), and climate action (SDG 13). By embedding sustainability into product design, operations, and partnerships, we aim to create long-term value for our clients, employees, and the communities we serve.", badge: null },
  { id: 'sec-2', sort_order: 1, title: '1. Circular Economy & E-Waste Stewardship', text: 'We are committed to minimizing electronic waste through responsible device lifecycle management. Our initiatives include partnerships with certified e-waste recyclers, refurbishment programs for retired hardware, and supplier requirements for take-back schemes. By 2027, we aim to divert 100% of our e-waste from landfills and extend the useful life of devices through repair, reuse, and responsible material recovery. We also work with clients to establish circular IT procurement policies that prioritize durability, repairability, and end-of-life recycling.', badge: 'COLLAPSIBLE' },
  { id: 'sec-3', sort_order: 2, title: '2. Decarbonizing Digital Infrastructure', text: 'Our digital infrastructure is being decarbonized through renewable energy procurement, energy-efficient data center design, and carbon-aware cloud architectures. We track Scope 1, 2, and 3 emissions and publish annual carbon footprint reports. Our target is a 50% reduction in absolute emissions by 2028. We optimize compute workloads to run during periods of low grid carbon intensity, consolidate underutilized servers, and invest in next-generation cooling technologies. Our cloud partners are selected partly based on their renewable energy commitments and carbon transparency.', badge: 'COLLAPSIBLE' },
  { id: 'sec-4', sort_order: 3, title: '3. Low-Carbon Service Delivery', text: 'We optimize our software and services for energy efficiency. From lightweight code deployments to edge computing strategies that reduce data transmission distances, every layer of our service delivery model is evaluated for carbon impact. We help clients measure and reduce the carbon footprint of their digital operations through sustainability dashboards, green software audits, and carbon-aware architecture guidance. Our engineering teams follow green coding practices that minimize CPU cycles, memory usage, and network transfers—reducing both cost and environmental impact.', badge: 'COLLAPSIBLE' },
  { id: 'sec-5', sort_order: 4, title: '4. Ecosystem Protection & Climate Resilience', text: 'Beyond our operational footprint, we invest in ecosystem restoration and climate resilience projects. This includes reforestation partnerships, water conservation programs in our offices, and climate-risk assessments for our supply chain. We align with the Task Force on Climate-related Financial Disclosures (TCFD) framework and integrate climate risk into our enterprise risk management process. Our community programs support climate-smart agriculture, wetland restoration, and biodiversity monitoring using our own technology platforms.', badge: 'COLLAPSIBLE' },
  { id: 'sec-6', sort_order: 5, title: '5. Social Impact: Enabling Client Sustainability', text: 'Our greatest impact comes from empowering clients to achieve their sustainability goals. Through Duqact, we provide supply chain transparency tools that reduce food waste and logistics emissions. Through FoundDocument, we enable paperless operations that save millions of pages annually. We measure the avoided emissions generated by client use of our platforms and publish these impact metrics in our annual ESG report. Our digital literacy programs also ensure that sustainability benefits are accessible to small businesses and informal sector operators across Africa.', badge: 'COLLAPSIBLE' },
  { id: 'sec-7', sort_order: 6, title: '6. Governance & Accountability', text: 'Sustainability governance is embedded in our board structure and executive compensation. Our ESG Committee meets quarterly to review targets, risks, and disclosures. We undergo third-party audits of our environmental data and maintain transparent reporting aligned with GRI and SASB standards. Our code of conduct applies to all employees, suppliers, and partners, with zero tolerance for greenwashing or misleading environmental claims. We maintain a whistleblower policy and independent oversight for all ESG-related disclosures.', badge: 'COLLAPSIBLE' }
];

const AdminSustainability = () => {
  const [sections, setSections] = useState(DEFAULT_SUSTAINABILITY_SECTIONS);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [activeSectionId, setActiveSectionId] = useState('1');
  const [expandedSections, setExpandedSections] = useState({ 1: true });
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingSection, setEditingSection] = useState(null);
  const [formData, setFormData] = useState({ sort_order: '', title: '', badge: '', text: '' });

  const getAuthHeaders = () => {
    const token = localStorage.getItem('cms_auth_token') || sessionStorage.getItem('cms_auth_token');
    return {
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
    };
  };

  const fetchSections = async () => {
    try {
      setLoading(true);
      const response = await api.get('/legal/sustainability/sections');
      if (response.data && Array.isArray(response.data) && response.data.length > 0) {
        setSections(response.data);
      } else {
        setSections(DEFAULT_SUSTAINABILITY_SECTIONS);
      }
    } catch (err) {
      setError(err.message);
      setSections(DEFAULT_SUSTAINABILITY_SECTIONS);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSections();
  }, []);

  const sortedSections = [...sections].sort((a, b) => Number(a.sort_order) - Number(b.sort_order));

  const filteredSections = sortedSections.filter(
    (sec) =>
      sec.title?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      sec.text?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const formatSectionNumber = (num, idx) => {
    return `${idx + 1}.`;
  };

  const cleanTitle = (rawTitle) => {
    if (!rawTitle) return '';
    return String(rawTitle).replace(/^(\d+[\.\s\-\)]*)+/g, '').trim();
  };

  const handleOpenAddModal = () => {
    setEditingSection(null);
    setFormData({ sort_order: '', title: '', badge: '', text: '' });
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (sec) => {
    setEditingSection(sec);
    setFormData({
      sort_order: sec.sort_order ?? '',
      title: sec.title || '',
      badge: sec.badge || '',
      text: sec.text || ''
    });
    setIsModalOpen(true);
  };

  const handleSaveSection = async (e) => {
    if (e) e.preventDefault();

    if (!formData.title?.trim() || !formData.text?.trim()) {
      alert('Please provide both a Section Title and Content.');
      return;
    }

    const cleanTitle = formData.title.replace(/^(\d+[\.\s\-\)]*)+/g, '').trim();
    const payload = {
      sort_order: formData.sort_order ? Number(formData.sort_order) : undefined,
      title: cleanTitle,
      badge: formData.badge.trim(),
      text: formData.text.trim()
    };

    const endpoint = editingSection
      ? `/legal/sustainability/section/${editingSection.id}`
      : '/legal/sustainability/section';

    console.log(`[DEBUG] Attempting ${editingSection ? 'PUT' : 'POST'} to: ${endpoint}`, payload);

    try {
      let res;
      if (editingSection) {
        res = await api.put(endpoint, payload, getAuthHeaders());
        setSections((prev) => prev.map((s) => (s.id === editingSection.id ? res.data : s)));
      } else {
        res = await api.post(endpoint, payload, getAuthHeaders());
        setSections((prev) => [...prev, res.data]);
      }

      setFormData({ sort_order: '', title: '', badge: '', text: '' });
      setEditingSection(null);
      setIsModalOpen(false);
    } catch (err) {
      console.error('[DEBUG] Save error details:', {
        status: err.response?.status,
        data: err.response?.data,
        url: err.config?.url
      });
      alert(`Save Failed: ${err.response?.data?.error || err.message || 'Server error'}`);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this section?')) return;
    try {
      await api.delete(`/legal/sustainability/section/${id}`, getAuthHeaders());
      setSections(sections.filter((s) => s.id !== id));
    } catch (err) {
      setError(err.message);
    }
  };

  const toggleExpand = (num) => {
    setExpandedSections((prev) => ({ ...prev, [num]: !prev[num] }));
  };

  return (
    <div style={{ width: '100%', minWidth: '100%', padding: '15px 20px', backgroundColor: '#fff' }}>
      <style>{`
        .toc-scroller::-webkit-scrollbar { width: 5px; }
        .toc-scroller::-webkit-scrollbar-track { background: #f1f1f1; border-radius: 4px; }
        .toc-scroller::-webkit-scrollbar-thumb { background: #6bb200; border-radius: 4px; }
        .toc-scroller::-webkit-scrollbar-thumb:hover { background: #4a8200; }
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
      `}</style>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: '12px', marginBottom: '15px', borderBottom: '1px solid #e9ecef', flexWrap: 'wrap', gap: '10px' }}>
        <div>
          <h2 style={{ color: '#6bb200', fontSize: '1.6rem', fontWeight: '700', margin: '0 0 2px 0' }}>
            Satesoft Sustainability
          </h2>
          <p style={{ color: '#6bb200', fontSize: '0.92rem', fontStyle: 'italic', fontWeight: '600', margin: '0 0 4px 0' }}>
            ESG Strategy &amp; Comprehensive Sustainability Framework
          </p>
          <div style={{ color: '#6c757d', fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase' }}>
            EFFECTIVE: 01.04.2025 &nbsp;&nbsp;•&nbsp;&nbsp; VERSION 1.0.0
          </div>
        </div>

        <div className="flex items-center gap-3">
          <input
            type="text"
            placeholder="Search sections..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-48 sm:w-64 text-xs bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#70B312]"
          />
          <button
            type="button"
            onClick={handleOpenAddModal}
            className="flex items-center gap-1.5 text-xs font-semibold text-white bg-[#70B312] hover:bg-[#5a9e0e] px-3.5 py-2 rounded-lg transition-colors shadow-sm shrink-0 cursor-pointer uppercase tracking-wide"
          >
            <span className="text-sm font-bold">+</span>
            <span>Add Section</span>
          </button>
          <button
            className="btn btn-sm text-white px-2 shadow-sm d-inline-flex align-items-center gap-1"
            style={{ backgroundColor: '#6bb200', fontWeight: '600', fontSize: '0.8rem', height: '29px' }}
            onClick={() => window.print()}
          >
            <i className="bi bi-printer"></i> Print
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', gap: '20px', alignItems: 'flex-start', width: '100%' }}>
        <div className="w-full lg:w-1/4 shrink-0">
          <div className="sticky top-6 bg-white border border-gray-200 rounded-xl p-4 shadow-sm max-h-[calc(100vh-6rem)] overflow-y-auto no-scrollbar">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">
              Table of Contents
            </h3>

            <nav className="space-y-1">
              {sortedSections.map((sec, idx) => (
                <a
                  key={sec.id}
                  href={`#sec-${sec.sort_order}`}
                  onClick={() => setActiveSectionId(String(sec.sort_order))}
                  className="flex items-center gap-2 p-2 rounded-lg text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-50 transition-colors"
                >
                  <span className="font-bold text-[#70B312] shrink-0">
                    {idx + 1}.
                  </span>
                  <span className="truncate">{cleanTitle(sec.title)}</span>
                </a>
              ))}
            </nav>
          </div>
        </div>

        <div style={{ flex: 1, minWidth: 0 }}>
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '15px',
              maxHeight: '440px',
              overflowY: 'auto',
              paddingRight: '10px',
            }}
          >
            {filteredSections.map((sec, idx) => {
              const isExpanded = expandedSections[sec.sort_order];
              const sectionLabel = formatSectionNumber(sec.sort_order, idx);

              return (
                <div key={sec.id} id={`sec-${sec.sort_order}`} style={{ paddingBottom: '12px', borderBottom: '1px solid #e9ecef' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                    <h5 style={{ color: '#6bb200', fontSize: '1.05rem', fontWeight: '700', margin: 0 }}>
                      {sectionLabel} {cleanTitle(sec.title)}
                    </h5>

                    <div style={{ display: 'flex', gap: '8px' }}>
                      <button
                        className="btn btn-sm btn-link p-0 text-decoration-none text-secondary"
                        style={{ fontSize: '0.8rem' }}
                        onClick={() => handleOpenEditModal(sec)}
                        title="Edit Section"
                      >
                        <i className="bi bi-pencil"></i>
                      </button>
                      <button
                        className="btn btn-sm btn-link p-0 text-decoration-none text-danger"
                        style={{ fontSize: '0.8rem' }}
                        onClick={() => handleDelete(sec.id)}
                        title="Delete Section"
                      >
                        <i className="bi bi-trash"></i>
                      </button>
                    </div>
                  </div>

                  {isExpanded ? (
                    <div>
                      <p style={{ color: '#212529', lineHeight: '1.5', fontSize: '0.88rem', whiteSpace: 'pre-line', margin: '0 0 6px 0' }}>
                        {sec.text}
                      </p>
                      <button
                        className="btn btn-link p-0 text-decoration-none fw-semibold d-inline-flex align-items-center gap-1"
                        style={{ color: '#6bb200', fontSize: '0.8rem' }}
                        onClick={() => toggleExpand(sec.sort_order)}
                      >
                        <i className="bi bi-x-circle"></i> Show Less
                      </button>
                    </div>
                  ) : (
                    <div>
                      <p style={{ color: '#6c757d', fontSize: '0.85rem', margin: '0 0 4px 0', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {sec.text?.slice(0, 100)}...
                      </p>
                      <button
                        className="btn btn-link p-0 text-decoration-none fw-semibold d-inline-flex align-items-center gap-1"
                        style={{ color: '#6bb200', fontSize: '0.8rem' }}
                        onClick={() => toggleExpand(sec.sort_order)}
                      >
                        <i className="bi bi-plus-circle"></i> Show More
                      </button>
                    </div>
                  )}
                </div>
              );
            })}

            <div style={{ textAlign: 'center', paddingTop: '15px' }}>
              <p style={{ color: '#6c757d', fontSize: '0.78rem', margin: '0 0 2px 0' }}>
                Confidential — Satesoft Corporation Limited
              </p>
              <p style={{ color: '#6bb200', fontSize: '0.82rem', fontWeight: '700', margin: 0 }}>
                Satesoft Corporation Limited — Your Innovation Partner
              </p>
            </div>
          </div>
        </div>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 z-[9999] bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-xl border border-slate-100 w-full max-w-lg overflow-hidden animate-in fade-in zoom-in-95 duration-150">

            <div className="px-6 pt-6 pb-4 flex items-center justify-between border-b border-slate-100">
              <h3 className="text-lg font-bold text-slate-900">
                {editingSection ? 'Edit Section' : 'Add New Section'}
              </h3>
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 text-lg font-semibold px-2"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSaveSection}>
              <div className="p-6 space-y-4 text-xs">
                <div>
                  <label className="block font-semibold text-slate-700 mb-1.5">
                    Sort Order
                  </label>
                  <input
                    type="text"
                    value={formData.sort_order}
                    onChange={(e) => setFormData({ ...formData, sort_order: e.target.value })}
                    placeholder="e.g. 13"
                    className="w-full bg-white border border-slate-200 rounded-lg p-3 text-slate-800 focus:outline-none focus:border-[#70B312] transition-colors"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-slate-700 mb-1.5">
                    Section Title
                  </label>
                  <input
                    type="text"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    placeholder="e.g. 21. New Section"
                    className="w-full bg-white border border-slate-200 rounded-lg p-3 text-slate-800 focus:outline-none focus:border-[#70B312] transition-colors"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-slate-700 mb-1.5">
                    Badge
                  </label>
                  <input
                    type="text"
                    value={formData.badge}
                    onChange={(e) => setFormData({ ...formData, badge: e.target.value })}
                    placeholder="e.g. COLLAPSIBLE or leave empty"
                    className="w-full bg-white border border-slate-200 rounded-lg p-3 text-slate-800 focus:outline-none focus:border-[#70B312] transition-colors"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-slate-700 mb-1.5">
                    Section Content
                  </label>
                  <textarea
                    rows={6}
                    value={formData.text}
                    onChange={(e) => setFormData({ ...formData, text: e.target.value })}
                    placeholder="Enter section body text..."
                    className="w-full bg-white border border-slate-200 rounded-lg p-3 text-slate-800 focus:outline-none focus:border-[#70B312] transition-colors leading-relaxed"
                  />
                </div>
              </div>

              <div className="px-6 py-4 bg-slate-50/50 flex justify-end gap-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-5 py-2.5 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 text-xs font-bold text-white bg-[#93cf3b] hover:bg-[#70B312] rounded-xl transition-colors shadow-sm uppercase tracking-wide"
                >
                  {editingSection ? 'Update Section' : '+ ADD SECTION'}
                </button>
              </div>
            </form>

          </div>
        </div>
      )}
    </div>
  );
};

export default AdminSustainability;
